### ISSUE TITLE
Documentar programación de LMK y AD

### ISSUE THREAD

**Issue by girlop** [TimingKeepers/ugr-scripts#2]

**Comment by jose-lj** [comment]
Me parece buena la iniciativa de publicar algo parecido a tutoriales, pero quizás deberíamos tener un repositorio (o alguna otra plataforma) sólo para eso.

**Comment by klyone** [comment]
@girlop @jose-lj o incluso podemos usar la wiki para eso si queréis y poner algunas notas para las diferentes herramientas.

@girlop: Recuerda poner en la descripción alguna cosa jejeje aunque sea un poco redundante para que los issues se queden autocontenidos.

**Comment by jose-lj** [comment]
Provisionalmente he añadido la documentación, ya que la tenemos generada, en una nueva rama de este mismo repositorio.

Se puede visitar [aquí](https://github.com/TimingKeepers/ugr-scripts/blob/joselj-doc/doc/zen-clock-programming.md).
